DROP DATABASE IF EXISTS employees;

CREATE DATABASE employees;

USE employees;

CREATE TABLE department (
    id INT UNSIGNED NOT NULL PRIMARY KEY, 
    name VARCHAR(30)
);

CREATE TABLE role (
    id INT UNSIGNED NOT NULL PRIMARY KEY, 
    title VARCHAR(30) UNIQUE NOT NULL,
    salary DECIMAL UNSIGNED NOT NULL,
    department_id INT UNSIGNED NOT NULL,
    FOREIGN KEY (department_id)
    REFERENCES department(id)
    ON DELETE CASCADE
);

CREATE TABLE employee (
    id INT AUTO_INCREMENT NOT NULL PRIMARY KEY, 
    first_name VARCHAR(30) UNIQUE NOT NULL,
    last_name VARCHAR(30) UNIQUE NOT NULL,
    role_id INT UNSIGNED NOT NULL,
    FOREIGN KEY (role_id)
    REFERENCES role(id) ON DELETE CASCADE
);

